---
# tasks file for firefox

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - bzip2

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "files{{ FIREFOX_DIR }}/firefox-80.0.tar.bz2"
    dest: '{{ FIREFOX_DIR }}'
    remote_src: no

- name: Create symbolic link 
  file:
    src: "{{ FIREFOX_DIR }}/firefox/firefox"
    dest: /usr/bin/firefox
    state: link
    force: yes